### ISSUE TITLE
Impurities / Documentation

### ISSUE THREAD

**Issue by srigas** [joselado/pyqula#3]
Hello, I'd first like to congratulate on your outstanding work. My MSc thesis concerned topological superconductors, and even though I've now moved on to Machine Learning in the industry, I still play around with physics whenever I have the time. This is how I found this repo and all I can say is that your open source work is remarkable.

First of all, I would like to ask if there is any way to help you with documentation about this huge project. Someone more experienced with code and theory may manage to find what they're looking for, but I fear that pre- or even post-graduate students may find some difficulty navigating, which is a shame since your code has a lot to offer them, both educationally and research-wise.

Secondly, I have a more specific question: I was wondering if you have created systematic ways to play around with impurities. I've seen some examples where you add a single impurity using the embedding class, however I haven't seen a more "organized" way to define impurities. For example, how would one go about defining a slab and then placing on top of it a chain of impurities with certain spin configurations (for example forming a helix)? Do you think this is something that can be done with the code as it is now, or do such examples require it to be expanded first?

Once again, thank you for your remarkable contribution. I'd be glad to be of any help, either with documentation, or with questions such as the aforementioned one. Keep it up and best of luck!

**Comment by joselado** [comment]
Hi srigas,

thank you for your message and for the kind feedback! It is great to hear that you found the software useful.

Thanks for the comment about the documentation. Having an in-depth documentation is certainly something on the to do list. The way the code is thought now is that the functionality is shown with examples in the examples folder, and there are also more detailed demonstration with Jupyter notebooks here
https://github.com/joselado/jyvaskyla_summer_school_2022
Having a detailed documentation would be great in the future. I can let you know once all the major development has stopped, so that writing some detailed documentation could be a nice next step.  

Regarding the impurities. Currently there is no specific module to work with impurities, but one needs to add as many as you want by hand to the Hamiltonian. This can be done both for periodic systems as well as for embedding objects. In principle with the current functionality one can add as many impurities as you want, yet of course it may be interesting to have a systematic library to do this in the future.

Thanks again for the comments and the feedback!

Best regards,
Jose
